### ISSUE TITLE
Python uses the install root even when building

### ISSUE THREAD

**Issue by hughie** [stonier/win_ros#68]
This can create bugs if in the build if you have old python modules lying around in the install root.

Bit of a mystery - no idea where it picks up the python path from.

**Comment by stonier** [comment]
Is it due to /cmake/templates/python_distutils_install.sh.in - it places the install path before the build path.

But is it a path sequence problem or a dependency problem (no genmsg in the dependency).

Unfortunately, I can't remember the exact error output and can't reproduce it. So let's leave this on the backburner until it happens again and then catch the exact error and find a reproducable case.

**Comment by stonier** [comment]
Reopen if necessary.
